language: node_js
# At this time, the travis trusty sudo environment works, but the sudo: false
# environment doesn't (it might with a bunch of apt packages).
sudo: required
dist: trusty

node_js:
  - '0.12'

addons:
  firefox: latest
  apt:
    packages:
      # I suspect that not all of these are necessary
      - mesa-utils
      - xvfb
      - libosmesa6

      - libgif-dev
      - libpng-dev

      - freeglut3-dev
      - libxmu-dev
      - libxi-dev
      - libxxf86vm-dev
      - libxrandr-dev

cache:
  directories:
    - node_modules
    - "$HOME/cache"

before_install:
  - CACHE="${HOME}/cache" CMAKE_VERSION=3.5.0 CMAKE_SHORT_VERSION=3.5 source ./scripts/install_cmake.sh
  - npm prune

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run build
  - npm run docs
  - mkdir _build
  - bash -c 'GEOJS_SERVE_TEST=true npm run start-test >/tmp/geojs_output.log 2>&1' &
  - until grep -s 'Forever processing file' /tmp/geojs_output.log; do sleep 1; done
  # Adding TEST_SAVE_IMAGE=all will allow image tests with no baseline images
  # to pass.  Only use this during development.
  # - export TEST_SAVE_IMAGE=all
  - ctest -S cmake/travis_build.cmake -VV || true
  - if [ -f _build/test_failed ] ; then false ; fi

after_success:
  - npm run codecov
  - pip install --user GitPython boto3
  - python $TRAVIS_BUILD_DIR/scripts/upload_notes.py --repo $TRAVIS_BUILD_DIR --upload $TRAVIS_BUILD_DIR/_build/build_notes.json

env:
  global:
    - secure: JYWs3zJV09uAb7CvX32pADRYTH2XqSGvImNEI6zVFxJxs9r0JsGgyOTz4PPBgs3dv1OjVBXqxu4GD2ZBKeo0Ax13ZnBNVR/BacupBtIwXbxp/FG2lr+WBzE0YnEBhAF/mW5DEkNBWJyLSiBlxYA5QFAAHYwb/GOADl+Z9Qi2FIU=
    - secure: on13Ka+3jkLDCXxqzxuT+CY4sPM0Zxfbe9M2F3LE0yhN2ww5vaBKdbTrzEWa0TOlBkM2qQUPAFybjHXfHeRyKpZDlsssjogH8YO5qx4zFRP5ZB9ny39QAqBsfZTuXt2WmOTLEcXkByYXVH8my/8ZqZqofSeBZsZdeauzoLbr0R0=
