language: node_js

node_js:
    - "0.10"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y cmake

script:
    - npm install
    - node_modules/.bin/grunt
    - git submodule init
    - git submodule update
    - mkdir _build
    - cd _build
    - cmake ..
    - ctest -VV -S ../cmake/travis_build.cmake
    - ctest -VV -S ../cmake/travis_submit.cmake
