language: node_js
sudo: False
node_js:
    - "0.12"

cache:
    directories:
        - node_modules

script:
    - npm prune
    - npm run build
    - ./node_modules/.bin/grunt docs
    - ./node_modules/.bin/grunt copy:jqueryui
    - npm run ci

after_success:
  - npm run codecov
