timezone: America/New_York
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: my_collection
    values:
      layout: ""

collections:
  example:
    output: true
  tutorial:
    output: true

# # otherwise some big files in this data folder will hang jekyll build
# exclude:
#   - data

keep_files:
  - data
